# Generated by Django 3.0.3 on 2020-02-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='listings_id',
            new_name='listing_id',
        ),
    ]
