# Generated by Django 3.0.3 on 2020-02-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200217_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(max_length=200),
        ),
    ]
